- docs/Getting Started/Connecting to a SDL Core/index.md
Fixes #6
Fixes a broken link to the relay guide.
> Fix link to Relay app guide

- docs/Displaying Information/Text Images and Buttons/index.md
Fixes #8 
This change updates the notification code to properly handle the notifications for an `SDLSoftButton` to include both `SDLOnButtonPress` and `SDLOnButtonEvent`.
> Handling Soft Button notifications

- docs/Getting Vehicle Data/index.md
Fixes #10 
This pull request **adds new content**.
This adds code for retrieving vehicle data.
> Added code for retrieving vehicle data.

- docs/Getting Started/Integration Basics/index.md
Fixes #20 
Fixes a link to the adding a lock screen page.
> Fixed link to lock screen page.

- docs/Getting Started/Connecting to a SDL Core/index.md
> Fix a typo in "Connecting to a SDL Core"

- docs/Getting Vehicle Data/index.md
Fixes
Fixed subscribeVehicleData init in Swift
> Fixed subscribeVehicleData init in Swift

- docs/Getting Started/SDK Configuration/index.md
Fixes #36 
Added Multisession string to the ea strings.
> added the multisession string

- docs/Mobile Navigation/Audio Streaming/index.md
- docs/Mobile Navigation/Video Streaming/index.md
Fixes #41 
This pull request adds new content.
Adds features `AudioStreamManager` and `CarWindow`.
> Update with 5.1 features

- docs/Mobile Navigation/Video Streaming/index.md
Fixes #44 
Improves the `CarWindow` documentation
> CarWindow improvements

- docs/Uploading Files and Graphics/index.md
Update swift code for 'Uploading Files' of iOS Docs
> Update Uploading Files Swift code for SDL 5.0

- docs/Getting Vehicle Data/index.md
Fixes #48 
Update Swift Code in 'Getting Vehicle Data' section of iOS Docs
> Update Getting Vehicle Data Swift code for SDL 5.0

- docs/Getting In-Car Microphone Audio/index.md
Fixes #48 
Update Swift Code in 'Getting In-Car Microphone Audio' section of iOS Docs
> Update Getting In-Car Microphone Audio Swift code for SDL 5.0 

- docs/Setting the Navigation Destination/index.md
Fixes #48 
Update Swift Code in 'Setting the Navigation Destination' section in iOS Docs
> Update Setting the Navigation Destination Swift code for SDL 5.0

- docs/Calling a Phone Number/index.md
Fixes #48 
Update Swift Code in 'Calling a Phone Number' section of the iOS Docs
> Update Calling a Phone Number Swift code for SDL 5.0 

- docs/Getting Started/Adapting to the Head Unit Language/index.md
- docs/Getting Started/Integration Basics/index.md
Update the swift code in the 'Getting Started' section of the iOS Docs
> Update Getting Started Swift code for SDL 5.0

- docs/Mobile Navigation/Audio Streaming/index.md
- docs/Mobile Navigation/Displaying Turn Directions/index.md
- docs/Mobile Navigation/Introduction/index.md
- docs/Mobile Navigation/Keyboard Input/index.md
- docs/Mobile Navigation/Supporting Haptic Input/index.md
- docs/Mobile Navigation/Touch Input/index.md
- docs/Mobile Navigation/Video Streaming/index.md
Update Swift Code in the 'Mobile Navigation' Section of the iOS Docs
> Update Mobile Navigation code for SDL 5.0

- docs/Getting Started/Adapting to the Head Unit Language/index.md
Fixes #60
This pull request **fixes existing content** and **adds new content**.
* Added documentation for the `SDLDidChangeLanguageNotification`
> Expand ChangeRegistration RPC documentation

- docs/Displaying Information/Creating the User Interface/index.md
Fixes #73
Fixed incorrect parameter names in the Screen Manager documentation
> Fixed incorrect parameter names in screen manager documentation

- docs/Getting In-Car Microphone Audio/index.md
Fixes https://github.com/smartdevicelink/sdl_ios_guides/issues/61
This pull request **[adds new content]**.
The audio stream format of AudioPassThru feature is added in "Getting In-Car Microphone Audio" page.
> Update APT document as per proposal SDL 0139

- docs/Developer Tools/Configuring SDL Logging/index.md
Fixes #76
This pull request **adds new content**.
Added section to **Developer Tools > Configuring SDL Logging** with instructions on how to create custom SDL logs in both Swift and Objective-C.
> Custom SDL Logging Instructions

- docs/Mobile Navigation/Video Streaming/index.md
Fixes #89 
This pull request **fixes existing content**  and  **adds new content**.
* Added the new`SDLVideoStreamSuspendedNotification` to the *Video Streaming* section.
* Separated the  *Video Streaming* section into two distinct sections: 
* CarWindow
* Custom Video Streaming Manager
> Added `SDLVideoStreamSuspendedNotification` to the Video Streaming Documentation

- docs/Displaying a User Interface/Main Screen Templates/index.md
One of the pieces of feedback from the CalHacks Hackathon was that finding these layouts was fairly difficult.  We should make the discovery of these layouts easier.
> Changing the text templates headlines

- docs/Developer Tools/Configuring SDL Logging/index.md
> Add additional file logging notes

- docs/Getting Started/Integration Basics/index.md
Fixes #108
This pull request adds new content.
Adds information on `additionalAppTypes` to Getting Started / Integration Basics
> Add information on `additionalAppTypes`

- docs/Displaying a User Interface/Text Images and Buttons/index.md
Fixes #113 
This pull request fixes existing content
Add example of setting screenmanager properties to nil
> Add example of setting screenmanager properties to nil

- docs/Video Streaming for Navigation Apps/Touch Input/index.md
Fixes #107 
This pull request fixes existing content.
Added some code for registering for `SDLTouchManager` callbacks.
> Add info on registering for touch event callbacks

- docs/Displaying a User Interface/Text Images and Buttons/index.md
Fixes #115
This pull request adds new content.
* Add information on the enum containing all static icon names.
* Add information on what fields accept static icons.
> Add a bit of information on static icons
